import React from "react";

interface Props { agreementId: string; customer: { fullName: string; phone: string; email: string | null }; vehicle: { chassisNumber: string; color: string; model: { make: string; modelName: string; year: number } }; salePrice: number; paymentMethod: string; notes: string }
const lkr = (value: number) => new Intl.NumberFormat("en-LK", { style: "currency", currency: "LKR", maximumFractionDigits: 0 }).format(value || 0);
const AgreementPreview: React.FC<Props> = ({ agreementId, customer, vehicle, salePrice, paymentMethod, notes }) => <article id="agreement-preview" className="mx-auto min-h-[780px] max-w-[720px] bg-white p-10 text-slate-800 shadow-2xl">
  <header className="border-b-4 border-amber-500 pb-5 text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-amber-600">OmniDrive</p><h1 className="mt-2 text-xl font-extrabold">VEHICLE SALES & HANDOVER AGREEMENT</h1><p className="mt-1 text-xs text-slate-500">{agreementId} · {new Date().toLocaleDateString()}</p></header>
  {[{ title:"CUSTOMER DETAILS", rows:[["Full name",customer.fullName],["Telephone",customer.phone],["Email",customer.email || "Not provided"]] },{ title:"VEHICLE CHASSIS & SPECIFICATION", rows:[["Chassis / VIN",vehicle.chassisNumber],["Vehicle",`${vehicle.model.make} ${vehicle.model.modelName} ${vehicle.model.year}`],["Colour",vehicle.color]] },{ title:"PAYMENT BREAKDOWN", rows:[["Final agreed price",lkr(salePrice)],["Payment method",paymentMethod.replace(/_/g," ")],["Notes",notes || "None"]] }].map((section) => <section key={section.title} className="mt-7"><h2 className="border-b border-slate-300 pb-1 text-xs font-bold tracking-wider">{section.title}</h2><div className="mt-3 grid grid-cols-2 gap-3">{section.rows.map(([label,value]) => <div key={label}><p className="text-[9px] uppercase text-slate-500">{label}</p><p className="text-sm font-semibold">{value}</p></div>)}</div></section>)}
  <section className="mt-7"><h2 className="border-b border-slate-300 pb-1 text-xs font-bold tracking-wider">TERMS & CONDITIONS</h2><ol className="mt-3 list-decimal space-y-1 pl-5 text-[11px] text-slate-600"><li>The buyer confirms inspection and acceptance of the vehicle in its present condition.</li><li>Ownership and risk transfer upon cleared payment and physical handover.</li><li>Both parties confirm the chassis and payment information recorded above.</li><li>Both parties agree to complete all applicable DMT/MTA transfer formalities.</li></ol></section>
  <div className="mt-20 grid grid-cols-2 gap-16 text-xs"><div className="border-t border-slate-600 pt-2">Buyer signature / Date</div><div className="border-t border-slate-600 pt-2">Authorised dealer / Date</div></div>
</article>;
export default AgreementPreview;
