import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const StatCard = ({ label, value, badge, badgeType = "muted", icon, }) => (_jsxs("div", { className: "card p-5 hover:shadow-card-hover transition-all duration-200 group", children: [_jsxs("div", { className: "flex items-start justify-between mb-3", children: [_jsx("span", { className: "text-2xl", children: icon }), badge && (_jsx("span", { className: badgeType === "success"
                        ? "badge-success"
                        : badgeType === "accent"
                            ? "badge-accent"
                            : "badge-muted", children: badge }))] }), _jsx("p", { className: "text-3xl font-bold text-white tracking-tight", children: value }), _jsx("p", { className: "text-muted text-sm mt-1", children: label })] }));
const WorkbenchPage = () => {
    return (_jsxs("div", { className: "h-full overflow-y-auto p-6 animate-fade-in", children: [_jsxs("div", { className: "mb-8", children: [_jsxs("div", { className: "flex items-center gap-3 mb-2", children: [_jsx("span", { className: "text-2xl", children: "\uD83D\uDCCA" }), _jsx("h2", { className: "text-2xl font-bold text-white tracking-tight", children: "Workbench" }), _jsx("span", { className: "badge-success", children: "Live" })] }), _jsx("p", { className: "text-muted text-sm", children: "Daily operations overview, KPIs, and dealership performance at a glance." })] }), _jsxs("div", { className: "grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8", children: [_jsx(StatCard, { icon: "\uD83D\uDE97", label: "Vehicles In Stock", value: "142", badge: "+12 this week", badgeType: "success" }), _jsx(StatCard, { icon: "\uD83D\uDCB0", label: "Revenue MTD", value: "$1.2M", badge: "\u25B2 18%", badgeType: "success" }), _jsx(StatCard, { icon: "\uD83D\uDC65", label: "Active Prospects", value: "38", badge: "Hot leads", badgeType: "accent" }), _jsx(StatCard, { icon: "\uD83D\uDD27", label: "In Repair Bay", value: "9", badge: "3 urgent", badgeType: "muted" })] }), _jsxs("div", { className: "card p-8 text-center", children: [_jsx("div", { className: "w-16 h-16 mx-auto mb-4 rounded-2xl bg-accent/10 border border-accent/20 flex items-center justify-center text-3xl", children: "\uD83D\uDCCA" }), _jsx("h3", { className: "text-white font-semibold text-lg mb-2", children: "Workbench Dashboard" }), _jsx("p", { className: "text-muted text-sm max-w-md mx-auto leading-relaxed", children: "Charts, recent activity feed, today's appointments, and deal pipeline will render here in Phase 2. The foundation layout and navigation are fully functional." }), _jsxs("div", { className: "flex gap-2 justify-center mt-6", children: [_jsx("span", { className: "badge-muted", children: "Phase 1 \u2713 Complete" }), _jsx("span", { className: "badge-accent", children: "Phase 2 \u2014 Charts & Feed" })] })] })] }));
};
export default WorkbenchPage;
