import React, { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import type { RecycleEntityType } from "../../../../shared/ipc";
import { invalidateDeletedData, useRecycleBin } from "../../hooks/useRecycleBin";

const tabs: Array<{ type?: RecycleEntityType; label: string }> = [{ label: "All Deleted Items" }, { type: "VEHICLE", label: "🚗 Inventory Units" }, { type: "CUSTOMER", label: "👥 Prospects & Customers" }, { type: "TASK", label: "✅ Tasks & Reminders" }, { type: "EXPENSE", label: "💰 Expenses & Financials" }];
const ago = (value: string) => { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return "just now"; if (seconds < 3600) return `${Math.floor(seconds / 60)} minutes ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)} hours ago`; return `${Math.floor(seconds / 86400)} days ago`; };

const RecycleBinPage: React.FC = () => {
  const [category, setCategory] = useState<RecycleEntityType | undefined>(); const client = useQueryClient();
  const { data: items = [], isLoading } = useRecycleBin(category);
  const restore = useMutation({ mutationFn: window.api.recyclebin.restore, onSuccess: () => invalidateDeletedData(client) });
  const purge = useMutation({ mutationFn: window.api.recyclebin.permanentDelete, onSuccess: () => invalidateDeletedData(client) });
  const empty = useMutation({ mutationFn: window.api.recyclebin.emptyBin, onSuccess: () => invalidateDeletedData(client) });
  return <section className="h-full overflow-y-auto p-5 lg:p-7"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-accent">Recovery center</p><h2 className="mt-1 text-2xl font-bold text-white">Recycle Bin — Deleted Items</h2><p className="mt-1 text-sm text-muted">Restore records or remove them permanently.</p></div><button disabled={!items.length || empty.isPending} onClick={() => { if (window.confirm("Permanently delete every item in the Recycle Bin? This action cannot be undone!")) empty.mutate(); }} className="rounded-lg border border-red-500/40 bg-red-500/10 px-4 py-2 text-sm font-semibold text-red-300 hover:bg-red-500/20">Empty Recycle Bin</button></div>
    <div className="mt-6 flex flex-wrap gap-2">{tabs.map((tab) => <button key={tab.label} onClick={() => setCategory(tab.type)} className={`rounded-full border px-4 py-2 text-xs font-semibold ${category === tab.type ? "border-accent bg-accent/10 text-accent" : "border-border bg-surface text-muted hover:text-white"}`}>{tab.label}</button>)}</div>
    <div className="card mt-5 overflow-hidden">{isLoading ? <p className="p-8 text-muted">Loading deleted items…</p> : !items.length ? <div className="p-14 text-center"><div className="text-4xl">🗑️</div><h3 className="mt-3 font-semibold text-white">Recycle Bin is empty</h3><p className="mt-1 text-sm text-muted">Deleted records will appear here.</p></div> : <div className="divide-y divide-border">{items.map((item) => <article key={`${item.entityType}-${item.id}`} className="flex flex-wrap items-center justify-between gap-4 px-5 py-4 hover:bg-surface-elevated/40"><div className="min-w-0"><div className="flex items-center gap-2"><span className="badge-muted">{item.entityType}</span><h3 className="truncate font-semibold text-white">{item.title}</h3></div><p className="mt-1 text-sm text-muted">{item.subtitle}</p>{item.detail && <p className="mt-0.5 text-xs text-subtle">{item.detail}</p>}<p className="mt-2 text-[10px] font-medium uppercase tracking-wider text-red-300">Deleted {ago(item.deletedAt)}</p></div><div className="flex gap-2"><button disabled={restore.isPending} onClick={() => restore.mutate({ entityType: item.entityType, id: item.id })} className="btn-ghost border border-border">↺ Restore</button><button disabled={purge.isPending} onClick={() => { if (window.confirm(`Permanently delete “${item.title}”? This action cannot be undone!`)) purge.mutate({ entityType: item.entityType, id: item.id }); }} className="rounded-lg border border-red-500/30 px-3 py-2 text-xs font-semibold text-red-300 hover:bg-red-500/10">❌ Delete Permanently</button></div></article>)}</div>}</div>
  </div></section>;
};
export default RecycleBinPage;
