import React, { useState } from "react";
import { useAddProspect, useAvailableVehicles } from "../../../hooks/useCrmQueries";

interface Props { open: boolean; onClose: () => void }
const initial = { fullName: "", phone: "", email: "", leadSource: "WALK_IN", pipelineStage: "NEW_LEAD", chassisNumber: "", quotedPrice: "", remarks: "" };
const AddProspectModal: React.FC<Props> = ({ open, onClose }) => {
  const [form, setForm] = useState(initial); const add = useAddProspect(); const { data: vehicles = [] } = useAvailableVehicles();
  const [isToday, setIsToday] = useState(true);
  const [entryDate, setEntryDate] = useState(() => new Date().toISOString().split("T")[0]);
  if (!open) return null;
  const set = (key: keyof typeof initial, value: string) => setForm((old) => ({ ...old, [key]: value }));
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/75 p-4" role="dialog" aria-modal="true"><div className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-border bg-surface shadow-card">
    <div className="sticky top-0 z-10 flex items-center justify-between border-b border-border bg-surface px-6 py-4"><div><p className="text-[10px] uppercase tracking-[.2em] text-subtle">CRM Intake</p><h2 className="text-lg font-bold text-white">Add New Prospect</h2></div><button className="btn-ghost" onClick={onClose}>×</button></div>
    <form className="space-y-4 p-6" onSubmit={async (e) => { e.preventDefault(); await add.mutateAsync({ ...form, email: form.email || undefined, chassisNumber: form.chassisNumber || undefined, quotedPrice: form.quotedPrice ? Number(form.quotedPrice) : undefined, remarks: form.remarks || undefined, createdAt: isToday ? new Date().toISOString() : new Date(entryDate).toISOString() }); setForm(initial); setIsToday(true); setEntryDate(new Date().toISOString().split("T")[0]); onClose(); }}>
      <div className="rounded-xl border border-border bg-background/40 p-4"><label className="flex cursor-pointer items-center gap-3 text-sm font-medium text-white"><input type="checkbox" checked={isToday} onChange={(e) => { const checked=e.target.checked; setIsToday(checked); if(checked)setEntryDate(new Date().toISOString().split("T")[0]); }} className="h-4 w-4 accent-accent" />Prospect entry date is Today</label><label className="mt-3 block text-xs text-muted">Inquiry / entry date<input required={!isToday} disabled={isToday} type="date" max={new Date().toISOString().split("T")[0]} value={entryDate} onChange={(e)=>setEntryDate(e.target.value)} className="input-dark mt-1 w-full disabled:cursor-not-allowed disabled:opacity-50" /></label></div>
      <div className="grid gap-4 md:grid-cols-2"><label className="text-xs text-muted">Full name *<input required className="input-dark mt-1 w-full" value={form.fullName} onChange={(e) => set("fullName",e.target.value)} /></label><label className="text-xs text-muted">Phone number *<input required type="tel" className="input-dark mt-1 w-full font-mono" placeholder="0771234567" value={form.phone} onChange={(e) => set("phone",e.target.value)} /></label><label className="text-xs text-muted">Email<input type="email" className="input-dark mt-1 w-full" value={form.email} onChange={(e) => set("email",e.target.value)} /></label><label className="text-xs text-muted">Lead source<select className="input-dark mt-1 w-full" value={form.leadSource} onChange={(e) => set("leadSource",e.target.value)}>{["WALK_IN","WHATSAPP","FACEBOOK","REFERRAL"].map((x) => <option key={x} value={x}>{x.replace(/_/g," ")}</option>)}</select></label>
        <label className="text-xs text-muted">Initial stage<select className="input-dark mt-1 w-full" value={form.pipelineStage} onChange={(e) => set("pipelineStage",e.target.value)}>{[["NEW_LEAD","New Lead"],["CONTACTED","Contacted"],["TEST_DRIVE","Test Drive Scheduled"],["NEGOTIATION","In Negotiation"]].map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><label className="text-xs text-muted">Vehicle unit of interest<select className="input-dark mt-1 w-full" value={form.chassisNumber} onChange={(e) => set("chassisNumber",e.target.value)}><option value="">No unit selected</option>{vehicles.map((v) => <option key={v.chassisNumber} value={v.chassisNumber}>{v.chassisNumber} · {v.model.make} {v.model.modelName}</option>)}</select></label><label className="text-xs text-muted md:col-span-2">Initial quoted price (LKR)<input type="number" min="1" className="input-dark mt-1 w-full" value={form.quotedPrice} onChange={(e) => set("quotedPrice",e.target.value)} /></label><label className="text-xs text-muted md:col-span-2">Remarks / notes<textarea rows={3} className="input-dark mt-1 w-full resize-none" value={form.remarks} onChange={(e) => set("remarks",e.target.value)} /></label></div>
      {add.error && <p className="rounded-lg bg-red-500/10 p-3 text-xs text-red-300">{add.error instanceof Error ? add.error.message : "Unable to add prospect."}</p>}<div className="flex justify-end gap-3 border-t border-border pt-4"><button type="button" className="btn-ghost" onClick={onClose}>Cancel</button><button disabled={add.isPending} className="btn-accent">{add.isPending ? "Saving..." : "Add Prospect"}</button></div>
    </form></div></div>;
};
export default AddProspectModal;
