import React from "react";
import type { UnifiedTask } from "../../../../../shared/ipc";
import { formatWhatsAppUrl } from "../../../lib/whatsapp";

interface Props { task: UnifiedTask; busy: boolean; onStatus: (status: "PENDING" | "IN_PROGRESS" | "COMPLETED") => void; onDetails: () => void; onDelete: () => void }
const actionLabels: Record<string, string> = { CALL: "📞 CALL", WHATSAPP: "💬 WHATSAPP", REPAIR_DISPATCH: "🔧 REPAIR DISPATCH", DOCUMENT_CHECK: "📄 DOCUMENT CHECK", VISIT: "🚗 VISIT" };
const lkr = (value: number) => new Intl.NumberFormat("en-LK", { style: "currency", currency: "LKR", maximumFractionDigits: 0 }).format(value);

const TaskCard: React.FC<Props> = ({ task, busy, onStatus, onDetails, onDelete }) => {
  const due = new Date(task.dueDate); const today = new Date(); today.setHours(0, 0, 0, 0); const end = new Date(today); end.setHours(23, 59, 59, 999);
  const overdue = task.status !== "COMPLETED" && due < today; const dueToday = due >= today && due <= end;
  const border = overdue || task.priority === "HIGH" ? "border-l-red-500" : dueToday ? "border-l-amber-400" : "border-l-slate-500";
  const quote = task.customer?.quotes[0]; const repair = task.chassis?.repairs[0];
  return <article className={`card border-l-4 ${border} p-4 ${task.status === "COMPLETED" ? "opacity-65" : ""}`}>
    <div className="flex flex-wrap items-start justify-between gap-2"><div><span className="badge-muted">{actionLabels[task.actionType] ?? task.actionType}</span><h3 className={`mt-2 font-semibold text-white ${task.status === "COMPLETED" ? "line-through" : ""}`}>{task.title}</h3></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${task.priority === "HIGH" ? "bg-red-500/15 text-red-300" : task.priority === "LOW" ? "bg-slate-500/15 text-slate-300" : "bg-amber-500/15 text-amber-300"}`}>{task.priority}</span></div>
    <div className="mt-3 rounded-lg border border-border bg-background/40 p-3 text-xs">{task.customer ? <><p className="font-semibold text-white">{task.customer.fullName}</p><p className="text-muted">{task.customer.phone}</p>{quote && <p className="mt-2 text-subtle">{quote.chassis.model.make} {quote.chassis.model.modelName} · {lkr(quote.quotedPrice)}</p>}<button onClick={() => window.open(formatWhatsAppUrl(task.customer!.phone, `Hello ${task.customer!.fullName}, following up from OmniDrive.`), "_blank")} className="mt-3 rounded-lg bg-emerald-600 px-3 py-1.5 font-semibold text-white hover:bg-emerald-500">💬 Open WhatsApp Chat</button></> : task.chassis ? <><p className="font-semibold text-white">{task.chassis.model.make} {task.chassis.model.modelName} {task.chassis.model.year}</p><p className="font-mono text-accent">{task.chassis.chassisNumber}</p><p className="mt-2 text-muted">Health: <span className="text-white">{task.chassis.healthStatus.replace(/_/g, " ")}</span></p>{repair && <p className="mt-1 text-subtle">{repair.description}</p>}</> : null}</div>
    {task.notes && <p className="mt-3 text-xs text-muted">{task.notes}</p>}<div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-border pt-3"><div><p className={`text-xs font-semibold ${overdue ? "text-red-300" : dueToday ? "text-amber-300" : "text-muted"}`}>{overdue ? "Overdue · " : dueToday ? "Due today · " : "Due · "}{due.toLocaleDateString()} {task.dueTime ?? ""}</p><select disabled={busy} value={task.status} onChange={(e) => onStatus(e.target.value as "PENDING" | "IN_PROGRESS" | "COMPLETED")} className="mt-2 rounded border border-border bg-surface-elevated px-2 py-1 text-[10px] text-white"><option value="PENDING">Pending</option><option value="IN_PROGRESS">In Progress</option><option value="COMPLETED">Completed</option></select></div><div className="flex items-center gap-2"><label className="flex cursor-pointer items-center gap-2 text-xs text-muted"><input type="checkbox" disabled={busy} checked={task.status === "COMPLETED"} onChange={(e) => onStatus(e.target.checked ? "COMPLETED" : "PENDING")} className="h-4 w-4 accent-emerald-500" /> Mark Done</label><button onClick={onDetails} className="btn-ghost text-xs">View Details →</button><button onClick={onDelete} className="btn-ghost text-xs text-red-300">🗑️ Delete</button></div></div>
  </article>;
};
export default TaskCard;
